# Generated by Django 5.2.8 on 2025-11-28 14:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_adminprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='admin_profile'),
        ),
    ]
