# Generated by Django 5.2.8 on 2025-11-27 08:12

import cloudinary.models
import documents.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[documents.models.validate_file_size, documents.models.validate_file_extension]),
        ),
    ]
