# Generated by Django 5.2.8 on 2025-11-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_required', models.CharField(choices=[('Plumbing', 'Plumbing'), ('Heating', 'Heating'), ('Electrical', 'Electrical'), ('Gardening', 'gardening'), ('Cleaning', 'cleaning'), ('Others', 'Others')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('budget_range', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
