# Generated by Django 5.2.8 on 2025-12-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='service_required',
            field=models.CharField(choices=[('Plumbing', 'Plumbing'), ('Heating', 'Heating'), ('Electrical', 'Electrical'), ('Gardening', 'gardening'), ('Cleaning', 'cleaning'), ('Roofing', 'roofing'), ('Painting', 'painting'), ('Others', 'Others')], max_length=20),
        ),
    ]
